### ISSUE TITLE
Partial payment vulnerability

### ISSUE THREAD

**Issue by smlu** [WietseWind/xrpayments.co#1]
When receiving payment the code does not check for partial payment transaction. This could lead to payment starvation where an attacker could send an amount less than  specified in the `Amount` field.
 [https://github.com/WietseWind/xrpayments.co/blob/cdcf788058fdb62b6f4750902cffe2887160126b/src/components/Home.vue#L237](https://github.com/WietseWind/xrpayments.co/blob/cdcf788058fdb62b6f4750902cffe2887160126b/src/components/Home.vue#L237)

One solution would be to first check if partial payment flag is set and then parse amount accordingly.
eg:  
```
if((tx.Flags & common.txFlags.Payment.PartialPayment) !== 0) {
    amount = parseAmount(tx.meta.delivered_amount)
} else {
    amount = parseAmount(tx.Amount)
}
```

See how ripple-lib does it: [parseDeliveredAmount(tx: any)](https://github.com/ripple/ripple-lib/blob/365de6d18a3d5f439c572c9287c2a8de9b43d37b/src/ledger/parse/utils.ts#L59)
Also see this function [parseAmount(amount: RippledAmount)](https://github.com/ripple/ripple-lib/blob/365de6d18a3d5f439c572c9287c2a8de9b43d37b/src/ledger/parse/amount.ts)
Would be good if code also checks in which currency the payment was received.

More on [partial payments](https://ripple.com/build/partial-payments/) and [robustly monitoring for payments](https://ripple.com/build/gateway-guide/#robustly-monitoring-for-payments).

**Comment by WietseWind** [comment]
@smlu Thank you very much! Fixed it right away, including the check for the received currency.

**Comment by WietseWind** [comment]
(Double thanks, fixed in in the https://xrptipbot.com as well 👍 )

**Comment by smlu** [comment]
Great 👍
